### Simple Math in R 

In [1]:
3-2

[1] 1

In [2]:
4^2

[1] 16

In [3]:
4*pi

[1] 12.56637

In [4]:
sin(4)

[1] -0.7568025

In [12]:
!(3==4)

[1] TRUE

In [15]:
(4 == 4)&& (3 > 12)

[1] FALSE

# Variable Assignment 

In [16]:
a<-3+3

In [18]:
print(a)

[1] 6


In [19]:
greetings <- "hey, buddy!"

In [20]:
print(greetings)

[1] "hey, buddy!"


In [21]:
some_logic <- TRUE

### The Vector

In [22]:
dat <- c(4,5,6,23,2)

In [23]:
print (dat)

[1]  4  5  6 23  2


In [24]:
v1 <- c(1,2,3)
v2 <- c(5,4,3)
v <- c(v1,v2)

In [25]:
print (v)

[1] 1 2 3 5 4 3


In [26]:
my_vec <- rep (0,10)

In [27]:
print(my_vec)

 [1] 0 0 0 0 0 0 0 0 0 0


In [28]:
m<- 1:20

In [32]:
v3<- seq(-10,10,2)

In [31]:
v3

[1] -10  -9  -8  -7  -6  -5

In [33]:
print(v3)

 [1] -10  -8  -6  -4  -2   0   2   4   6   8  10


In [34]:
v3

[1] -10  -8  -6  -4  -2   0   2   4   6   8  10

In [35]:
print (seq (-10,10,2))

 [1] -10  -8  -6  -4  -2   0   2   4   6   8  10


## CHALLENGE QUESTIONS

## Q1

In [39]:
u<-c(-2:2)

In [40]:
print(u)

[1] -2 -1  0  1  2


In [41]:
u<- seq(-2,2)

In [43]:
print (u)

[1] -2 -1  0  1  2


## Indexing and Slicing 

In [44]:
v<- rnorm(5)

In [45]:
v

[1]  1.139629 -1.661221  1.180562 -0.837497  0.638138

In [46]:
v[2]

[1] -1.661221

In [47]:
v [1:3]

[1]  1.139629 -1.661221  1.180562

In [48]:
v

[1]  1.139629 -1.661221  1.180562 -0.837497  0.638138

In [49]:
v[4]

[1] -0.837497

In [50]:
v[2:5]

[1] -1.661221  1.180562 -0.837497  0.638138

In [54]:
indces <- c(1,3)
print (indces)
v[indces]

[1] 1 3


[1] 1.139629 1.180562

In [51]:
v[c(1,3)]

[1] 1.139629 1.180562

In [52]:
print (v)

[1]  1.139629 -1.661221  1.180562 -0.837497  0.638138


In [53]:
v[-3]

[1]  1.139629 -1.661221 -0.837497  0.638138

## Assignment 

In [55]:
u<- c(5,6,8,22)

In [56]:
u[1]<- 0

In [57]:
print (u)

[1]  0  6  8 22


In [58]:
u3 <- u[1:3]

In [59]:
print (u3)

[1] 0 6 8


## challenge problem 2

In [61]:
v <- c(10,20,30)

In [62]:
print (v)

[1] 10 20 30


In [64]:
v[1]<- 0
v[2]<- 0 
print (v)

[1]  0  0 30


In [65]:
v[1:2] <-0
print (v)

[1]  0  0 30


##problem 3

In [80]:
v1<- c(10,20,30,40,50)
idx <- c(1,3,5)
v2 <- v1[idx]
print (v1)
print (v2)

[1] 10 20 30 40 50
[1] 10 30 50


In [75]:
v2 <- v1[-c(2,4)]
print (v2)

[1] 10 30 50


In [76]:
v2<-v1[c(1,3,5)]
print (v2)

[1] 10 30 50


In [84]:
v1 <- seq (10,50,10) # this is creating a vector 
idx <- c (TRUE, FALSE, TRUE, FALSE, TRUE)
v2 <- v1[idx]
print (v2)

[1] 10 30 50


### Vectorization of Operation 

In [90]:
v<- c(44, 55, 66)
v2<-v-20
print (v2)

[1] 24 35 46


In [87]:
v*2

[1]  88 110 132

In [88]:
v/5

[1]  8.8 11.0 13.2

In [89]:
v > 50

[1] FALSE  TRUE  TRUE

## Useful Operation on Vectors

In [91]:
v <- rnorm (10)

In [92]:
print (v)

 [1] -0.13423335 -0.85994964 -0.89054407  0.55478107 -1.23372606  0.03072534
 [7]  0.17584505  1.03338810  0.58837520 -0.44917856


In [94]:
n<-length (v)

In [95]:
print (n)

[1] 10


In [96]:
sum (v)

[1] -1.184517

In [97]:
max (v)

[1] 1.033388

In [98]:
min (v)

[1] -1.233726

In [102]:
xbar <-mean(v)
print (xbar)

[1] -0.1184517


In [106]:
s<- sd (v)

In [107]:
print(s)

[1] 0.73695


# The Matrix

In [108]:
x1<- c(4,5,6)
x2 <- c(55,55,77)

In [111]:
m<- cbind (x1,x2)
print (m)  # m is a 3*2 matrix

     x1 x2
[1,]  4 55
[2,]  5 55
[3,]  6 77


In [112]:
m2 <- rbind (x1,x2)

In [113]:
print (m2)

   [,1] [,2] [,3]
x1    4    5    6
x2   55   55   77


In [116]:
a <- matrix (0,nrow=5, ncol=3)

In [117]:
print (a)

     [,1] [,2] [,3]
[1,]    0    0    0
[2,]    0    0    0
[3,]    0    0    0
[4,]    0    0    0
[5,]    0    0    0


In [118]:
dat <- rnorm (15)

In [123]:
b <- matrix ("foo", ncol=3, nrow=5)

In [124]:
print (b)

     [,1]  [,2]  [,3] 
[1,] "foo" "foo" "foo"
[2,] "foo" "foo" "foo"
[3,] "foo" "foo" "foo"
[4,] "foo" "foo" "foo"
[5,] "foo" "foo" "foo"


### Indexing in Matrices

In [125]:
dat <- sample (12)

In [126]:
m <- matrix (dat, ncol =3)

In [127]:
print (m)

     [,1] [,2] [,3]
[1,]    3   11   12
[2,]    6    8    2
[3,]    9    7    5
[4,]    4   10    1


In [129]:
m[2,3]

[1] 2

In [130]:
m [1:2,3]

[1] 12  2

In [131]:
m[1,]

[1]  3 11 12

In [133]:
m[,3]<-0

In [134]:
print (m)

     [,1] [,2] [,3]
[1,]    3   11    0
[2,]    6    8    0
[3,]    9    7    0
[4,]    4   10    0


In [135]:
m[1:2,2]<- 99

In [136]:
print (m)

     [,1] [,2] [,3]
[1,]    3   99    0
[2,]    6   99    0
[3,]    9    7    0
[4,]    4   10    0


In [138]:
num_rows <-nrow(m)

In [140]:
print (num_rows)

[1] 4


In [141]:
colMeans(m)

[1]  5.50 53.75  0.00

In [142]:
rowSums(m)

[1] 102 105  16  14

### The Data Frame

In [154]:
id <- seq (4)
score <- rnorm (4)
names <- c("john", "paul", "george", "ringo")
vocals <- c (TRUE, TRUE, FALSE, FALSE)
dset <- data.frame (id, names, score, vocals, stringsAsFactors = FALSE)

In [155]:
print (dset)

  id  names      score vocals
1  1   john  1.5342155   TRUE
2  2   paul -0.3502210   TRUE
3  3 george  0.1053435  FALSE
4  4  ringo  1.1078366  FALSE


In [156]:
dset [1,2]

[1] "john"

In [157]:
dset$names

[1] "john"   "paul"   "george" "ringo"